name: Manual Build and Release XLibre Packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Packages 📦
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone void-packages
        run: git clone --depth=1 https://github.com/void-linux/void-packages.git

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar xz-utils ca-certificates

      - name: Download and install XBPS static binaries
        run: |
          wget https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz
          sudo install -Dm755 usr/bin/* /usr/local/bin/

      - name: Cache XBPS hostdir
        id: cache-hostdir
        uses: actions/cache@v4
        with:
          path: void-packages/hostdir
          key: xbps-hostdir-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('void-packages/xbps-src', 'void-packages/common/bootstrap/**', 'srcpkgs/**/*.template') }}

      - name: Bootstrap XBPS-src
        if: steps.cache-hostdir.outputs.cache-hit != 'true'
        working-directory: void-packages
        run: |
          export XBPS_ARCH=x86_64
          ./xbps-src binary-bootstrap

      - name: Copy templates
        run: |
          mkdir -p void-packages/srcpkgs
          cp -r srcpkgs/* void-packages/srcpkgs/ 2>/dev/null || true

      - name: Allow restricted packages
        working-directory: void-packages
        run: echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf

      - name: Build xlibre-xserver
        working-directory: void-packages
        run: ./xbps-src pkg xlibre-xserver

      - name: Index local repository
        working-directory: void-packages
        run: xbps-rindex -a hostdir/binpkgs/*.xbps

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: xlibre-packages
          path: void-packages/hostdir/binpkgs/*.xbps
